---
title: "Dokumentasjon for utregning av RAND-12-skåring"
author: "Stian Tufte Veisene"
output:
  html_document:
  css: H:\kvalreg\felles\latex-klassar\markdown-stilsett\kvalreg-stilsett.css
theme: flatly
toc: yes
word_document: default
editor_options: 
  chunk_output_type: console
---

# Innledning

PROM-senteret har utarbeidet en manual/SPSS-syntaks for skåring av RAND-12/SF-12.
Dette dokumentet er ment som et «gå-til-dokument» når man lurer på noe om 
RAND-12/SF-12 i kvalitetsregistersammenheng, da hovedsaklig når man skal benytte
denne manualen/SPSS-syntaksen, men også for generell informasjon om RAND-12/SF-12. 

Link til Pasientrapporterte data [https://www.kvalitetsregistre.no/pasientrapporterte-data#skaring-av-rand-12sf-12]

# RAND-12-skjemaet

RAND-12/SF-12 er spørreskjema med 12 spørsmål som måler livskvalitet - både
fysisk og mental. RAND-12/SF-12 er forkortede versjoner som av RAND-36/SF-36 
(som er den opprinnelige versjonen med 36 spørsmål). Spørreskjemaene SF-12 og 
SF-36har samme spørsmål som RAND-12 og RAND-36, men har en annen anbefalt 
skåringsalgoritme (?) og er i tillegg lisensbelagt.  

Link til RAND-12 [https://www.kvalitetsregistre.no/sites/default/files/https-/www.fhi.no/globalassets/dokumenterfiler/tema/brukererfaring/norsk-rand-12.pdf]

# Manual/SPSS-syntaks

Under «Generelle instrument» på nettsiden 
[https://www.kvalitetsregistre.no/pasientrapporterte-data#skaring-av-rand-12sf-12] 
ligger manualen for skåring av RAND-12. SPSS-syntaksen finnes her 
[https://www.kvalitetsregistre.no/sites/default/files/rand12_script.txt].

Manglende verdier, alt må være besvart (SYSMIS, ifelse)

For at skriptet skal fungere må 
variabelnavnene i SPSS-datafilen være de samme som i skriptet 
(GH1, PF02, PF04, RP2, RP3, RE2, RE3, BP2, MH3, VT2, MH4, SF2). Det er valgfritt om
man velger å bruke små eller store bokstaver. 

Selve skriptet har ingen test / gir ingen advarsel ved ugyldige verdier, men det 
står i kommentert i starten av skriptet at dette må sjekkes og korrigeres før 
skriptet kjøres. Om man ikke sjekker dette før skriptet kjøres, og det finnes 
ugyldige verdier, vil det føre til at det ikke blir regnet ut en skår for skjemaene 
som inneholder en eller flere ugyldige verdier - og ingen advarsel vil bli gitt. Se  
[https://www.kvalitetsregistre.no/sites/default/files/attachments/norsk_rand-12_m_koder.pdf]
for mulige/gyldige verdier.

I spørsmål/variabel 1, 5, 6a og 6b tilsvarer lav verdi god helse, mens i resten av 
spørsmålene tilsvarer lav verdi dårlig helse. På grunn av dette inverteres 
disse 4 variablene i starten på SPSS-skriptet slik at lav verdi tilsvarer dårlig 
helse for alle 12 variablene.

Neste steg i skriptet er at det opprettes en ny variabel for hvert svaralternativ 
(utenom for det alternativet med høyest verdi) i de 12 spørsmålene. F.eks. for
spørsmål 2a betyr dette at det opprettes 2 nye variabler, hvor den første av de får 
verdien 1 dersom det er krysset av på første svaralternativ («Ja, begrenser meg mye»),
og verdien 0 ellers. Den andre variabelen får verdien 1 dersom det er krysset av
på andre alternativ («Ja, begrenser meg litt»), og verdien 0 ellers. Grunnen til
denne kategoriseringen er at hvert svaralternativ (bortsett fra det med høyest verdi - utdype)
påvirker sumskåren med ulike vekter. Artikkelen som SPSS-syntaksen er basert på finnes her
[https://www.ncbi.nlm.nih.gov/pubmed/17825096]. Tabell 5 i artikkelen viser 
regresjonskoeffisientene (vektene) for hver variabel.

# Deskriptiv skåring-statistikk



