#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom dplyr across
#' @importFrom dplyr add_count
#' @importFrom dplyr anti_join
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr group_cols
#' @importFrom dplyr group_indices
#' @importFrom dplyr group_size
#' @importFrom dplyr group_vars
#' @importFrom dplyr groups
#' @importFrom dplyr if_else
#' @importFrom dplyr last
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr n
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom dplyr tally
#' @importFrom dplyr ungroup
#' @importFrom forcats fct_inorder
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_light
#' @importFrom ggplot2 theme_set
#' @importFrom ggplot2 update_geom_defaults
#' @importFrom methods as
#' @importFrom methods is
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dbl
#' @importFrom purrr map_lgl
#' @importFrom purrr pluck
#' @importFrom purrr pmap
#' @importFrom purrr possibly
#' @importFrom purrr walk
#' @importFrom Rdpack reprompt
#' @importFrom readr col_character
#' @importFrom readr col_integer
#' @importFrom readr locale
#' @importFrom readr read_delim
#' @importFrom readr read_lines
#' @importFrom rlang !!
#' @importFrom stats confint
#' @importFrom stats df
#' @importFrom stats glm
#' @importFrom stats na.omit
#' @importFrom stats sd
#' @importFrom stats setNames
#' @importFrom stats t.test
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_flatten_comma
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_split_fixed
#' @importFrom stringr str_sub
#' @importFrom stringr str_subset
#' @importFrom stringr str_to_lower
#' @importFrom tibble add_column
#' @importFrom tibble add_row
#' @importFrom tibble as_tibble
#' @importFrom tibble rowid_to_column
#' @importFrom tibble tibble
#' @importFrom tibble tribble
#' @importFrom tidyr fill
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr unnest
#' @importFrom tidyselect all_of
#' @importFrom tidyselect where
#' @importFrom utils capture.output
#' @importFrom utils data
#' @importFrom utils hasName
#' @importFrom utils head
#' @importFrom utils packageVersion
## usethis namespace: end
NULL
