#' @keywords internal
"_PACKAGE"

## usethis namespace: start
#' @importFrom colorspace coords
#' @importFrom dplyr across
#' @importFrom dplyr add_count
#' @importFrom dplyr anti_join
#' @importFrom dplyr arrange
#' @importFrom dplyr bind_cols
#' @importFrom dplyr bind_rows
#' @importFrom dplyr case_when
#' @importFrom dplyr count
#' @importFrom dplyr desc
#' @importFrom dplyr distinct
#' @importFrom dplyr filter
#' @importFrom dplyr full_join
#' @importFrom dplyr group_by
#' @importFrom dplyr group_cols
#' @importFrom dplyr group_indices
#' @importFrom dplyr group_size
#' @importFrom dplyr group_vars
#' @importFrom dplyr groups
#' @importFrom dplyr if_else
#' @importFrom dplyr intersect
#' @importFrom dplyr last
#' @importFrom dplyr left_join
#' @importFrom dplyr mutate
#' @importFrom dplyr mutate_at
#' @importFrom dplyr n
#' @importFrom dplyr n_distinct
#' @importFrom dplyr pull
#' @importFrom dplyr relocate
#' @importFrom dplyr rename
#' @importFrom dplyr select
#' @importFrom dplyr slice
#' @importFrom dplyr summarise
#' @importFrom dplyr summarise_at
#' @importFrom dplyr tally
#' @importFrom dplyr transmute_at
#' @importFrom dplyr ungroup
#' @importFrom dplyr vars
#' @importFrom ggplot2 aes
#' @importFrom ggplot2 coord_flip
#' @importFrom ggplot2 element_blank
#' @importFrom ggplot2 element_text
#' @importFrom ggplot2 geom_col
#' @importFrom ggplot2 geom_histogram
#' @importFrom ggplot2 ggplot
#' @importFrom ggplot2 margin
#' @importFrom ggplot2 scale_x_continuous
#' @importFrom ggplot2 scale_y_continuous
#' @importFrom ggplot2 theme
#' @importFrom ggplot2 theme_light
#' @importFrom ggplot2 theme_set
#' @importFrom ggplot2 update_geom_defaults
#' @importFrom glue glue
#' @importFrom knitr knit
#' @importFrom lintr ids_with_token
#' @importFrom lintr Lint
#' @importFrom lintr Linter
#' @importFrom lintr with_id
#' @importFrom lubridate as_date
#' @importFrom magrittr %>%
#' @importFrom purrr map
#' @importFrom purrr map_chr
#' @importFrom purrr map_dbl
#' @importFrom purrr map_df
#' @importFrom purrr map_lgl
#' @importFrom purrr pluck
#' @importFrom purrr pmap
#' @importFrom purrr possibly
#' @importFrom purrr walk
#' @importFrom qicharts2 qic
#' @importFrom Rdpack reprompt
#' @importFrom readr col_character
#' @importFrom readr col_integer
#' @importFrom readr read_lines
#' @importFrom rlang !!
#' @importFrom rlang enexpr
#' @importFrom rlang enquo
#' @importFrom rlang eval_bare
#' @importFrom rlang expr
#' @importFrom rlang has_name
#' @importFrom rlang is_empty
#' @importFrom rlang maybe_missing
#' @importFrom rlang new_function
#' @importFrom rlang quo_name
#' @importFrom rlang quo_text
#' @importFrom rlang quos
#' @importFrom rlang sym
#' @importFrom rlang syms
#' @importFrom ruler any_breaker
#' @importFrom ruler cell_packs
#' @importFrom ruler col_packs
#' @importFrom ruler data_packs
#' @importFrom ruler expose
#' @importFrom ruler get_report
#' @importFrom ruler rules
#' @importFrom stringr str_c
#' @importFrom stringr str_detect
#' @importFrom stringr str_flatten
#' @importFrom stringr str_replace
#' @importFrom stringr str_replace_all
#' @importFrom stringr str_split
#' @importFrom stringr str_split_fixed
#' @importFrom stringr str_sub
#' @importFrom stringr str_subset
#' @importFrom stringr str_to_lower
#' @importFrom styler tidyverse_math_token_spacing
#' @importFrom styler tidyverse_reindention
#' @importFrom styler tidyverse_style
#' @importFrom tibble add_row
#' @importFrom tibble as_tibble
#' @importFrom tibble rowid_to_column
#' @importFrom tibble tibble
#' @importFrom tibble tribble
#' @importFrom tidyr fill
#' @importFrom tidyr nest
#' @importFrom tidyr pivot_longer
#' @importFrom tidyr pivot_wider
#' @importFrom tidyr replace_na
#' @importFrom tidyr unnest
#' @importFrom tidyselect all_of
#' @importFrom tidyselect where
## usethis namespace: end
NULL
